### ISSUE TITLE
C++ in OpenCL kernels/ .cl files

### ISSUE THREAD

**Issue by mikulcak** [Galarius/vscode-opencl#47]
Hi,

less of an issue, more of a question, I suppose, I hope that's alright. I am using your great extension together with an LLVM-Spir-V translation workflow for offline compilation of OpenCL kernels using C++ language features. However, the C++ components of the OpenCL kernels are marked as errors by your extension. Is there an option that I a missing that would enable support for things like `auto`, namespaces, etc. in `.cl` files?

Thank you!

**Comment by Galarius** [comment]
Hi, @mikulcak. Would adding `-cl-std=CLC++` to `OpenCL.server.buildOptions` make a difference?

**Comment by mikulcak** [comment]
Hi @Galarius, that didn't work, unfortunately. The log says `Error parsing value of -cl-std flag!`. However, this makes sense to me, as the first OpenCL device detected by your included `clinfo` does not support compilation of kernels with C++ functionality (it's an Nvidia card, they don't support that OpenCL extension, unfortunately). Another device, namely the Intel CPU runtime I have installed as well, supports it. Could that be the reason the language server throws this error?

**Comment by Galarius** [comment]
@mikulcak, yes, this could be the reason, because currently the language server selects an OpenCL device with the highest power index, which equals to `maxComputeUnits` * `maxClockFrequency`. You can enable `OpenCL.server.debug.enableFileLogging` or change the value of `OpenCL.trace.server` to `verbose` to see, which device is used for diagnostics.

In any case, the ability to specify the desired OpenCL device would be a useful addition to the language server.

**Comment by Galarius** [comment]
OpenCL device can be selected for kernel diagnostics in version [0.8.0](https://github.com/Galarius/vscode-opencl/releases/tag/0.8.0).
