### ISSUE TITLE
opencl-language-server complaining about libc.so.6 version after upgrading to 0.8.0

### ISSUE THREAD

**Issue by hemingchen** [Galarius/vscode-opencl#55]
Hi, 
I started seeing the following error after upgrading to v0.8.0 a couple days ago:

```
[Error: 1] $HOME/.vscode-server/extensions/galarius.vscode-opencl-0.8.0/bin/linux/opencl-language-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by $HOME/.vscode-server/extensions/galarius.vscode-opencl-0.8.0/bin/linux/opencl-language-server)
$HOME/.vscode-server/extensions/galarius.vscode-opencl-0.8.0/bin/linux/opencl-language-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by $HOME/.vscode-server/extensions/galarius.vscode-opencl-0.8.0/bin/linux/opencl-language-server)
$HOME/.vscode-server/extensions/galarius.vscode-opencl-0.8.0/bin/linux/opencl-language-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by $HOME/.vscode-server/extensions/galarius.vscode-opencl-0.8.0/bin/linux/opencl-language-server)
```

(Masked actual path to home with $HOME)

It seems like the newest `opencl-language-server` binary was compiled against a bigger version of libc, which is higher than the one (v2.31) currently available on Ubuntu 20.04.

**Comment by Galarius** [comment]
Hi @hemingchen, the binary was built on `ubuntu-latest` using [this workflow](https://github.com/Galarius/opencl-language-server/blob/afa2d1066f31d9db4ac8ef6f2c9147cb8f61a87e/.github/workflows/release.yml#L35). `ubuntu-latest` is Ubuntu **22.04** since `November 9, 2022` according to this [announcement](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/). I'll switch the runner to `ubuntu-20.04`.

**Comment by hemingchen** [comment]
Many thanks!
